// <auto-generated />
using System;
using FamilyLearning.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyLearning.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    [Migration("20261006110141_AddTaskSessions")]
    partial class AddTaskSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("FamilyLearning.Api.Features.Activities.ActivityDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveOperationId")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReleasedSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleasedSourceRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "UpdatedAtUtc");

                    b.ToTable("ActivityDrafts");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Activities.GenerationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Failure")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("OriginalRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftId")
                        .IsUnique()
                        .HasFilter("Status IN ('queued', 'calling')");

                    b.HasIndex("FinishedAtUtc")
                        .HasFilter("ArtifactsJson IS NOT NULL");

                    b.HasIndex("DraftId", "CreatedAtUtc");

                    b.HasIndex("FamilyId", "OperationKey")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("GenerationOperations");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "SnapshotId")
                        .IsUnique();

                    b.HasIndex("FamilyId", "ChildId");

                    b.HasIndex("FamilyId", "SnapshotId");

                    b.HasIndex("ChildId", "CreatedAtUtc", "Id");

                    b.HasIndex("FamilyId", "CreatedAtUtc", "Id");

                    b.HasIndex("ChildId", "Status", "CreatedAtUtc", "Id");

                    b.HasIndex("FamilyId", "Status", "CreatedAtUtc", "Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Assignments.TaskSession", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByParentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoringPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.ToTable("TaskSessions");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "CreatedAtUtc", "Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.ChildActivation", b =>
                {
                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("ChildActivations");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.ChildDeviceGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "CreatedAtUtc", "Id");

                    b.ToTable("ChildDeviceGrants");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Instances.TaskSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DraftCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedInputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceDraftId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceDraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceDraftId")
                        .IsUnique();

                    b.HasIndex("FamilyId", "ReviewedAtUtc");

                    b.ToTable("TaskSnapshots");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Templates.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "CreatedAtUtc");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Templates.TaskTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique();

                    b.ToTable("TaskTemplateVersions");
                });

            modelBuilder.Entity("FamilyLearning.Api.Infrastructure.Auth.ParentUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FamilyLearning.Api.Infrastructure.Persistence.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Activities.ActivityDraft", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Persistence.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Activities.GenerationOperation", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Activities.ActivityDraft", null)
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Assignments.Assignment", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Children.Child", "Child")
                        .WithMany()
                        .HasForeignKey("FamilyId", "ChildId")
                        .HasPrincipalKey("FamilyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyLearning.Api.Features.Instances.TaskSnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("FamilyId", "SnapshotId")
                        .HasPrincipalKey("FamilyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Assignments.TaskSession", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Assignments.Assignment", "Assignment")
                        .WithOne("Session")
                        .HasForeignKey("FamilyLearning.Api.Features.Assignments.TaskSession", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.Child", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Persistence.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.ChildActivation", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Children.Child", null)
                        .WithOne()
                        .HasForeignKey("FamilyLearning.Api.Features.Children.ChildActivation", "ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Children.ChildDeviceGrant", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Children.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Instances.TaskSnapshot", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Persistence.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Templates.TaskTemplate", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Persistence.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Templates.TaskTemplateVersion", b =>
                {
                    b.HasOne("FamilyLearning.Api.Features.Templates.TaskTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Infrastructure.Auth.ParentUser", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Persistence.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Auth.ParentUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Auth.ParentUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FamilyLearning.Api.Infrastructure.Auth.ParentUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyLearning.Api.Features.Assignments.Assignment", b =>
                {
                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
