import { expect, test } from '@playwright/test';

test('parent creates a template and reopens the same saved draft on a narrow screen', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('TestOnly!Parent12345');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A fresh page for your family' })).toBeVisible();
  await page.getByRole('link', { name: 'Create your first template' }).click();
  await page.getByLabel('Template name').fill('Our times tables');
  await page.getByLabel('Starting difficulty').selectOption('easy');
  await page.getByRole('button', { name: 'Save template', exact: true }).click();
  await page.getByLabel('Number of questions', { exact: true }).fill('3');
  await page.getByRole('button', { name: 'Generate a draft' }).click();
  await expect(page.getByText('Draft saved', { exact: true })).toBeVisible();
  const questions = await page.locator('.question-prompt').allTextContents();
  expect(questions).toHaveLength(3);
  await page.reload();
  await expect(page.locator('.question-prompt')).toHaveText(questions);
  await page.getByText('Show answer', { exact: true }).first().click();
  await expect(page.locator('details').first()).toHaveAttribute('open', '');
  await page.setViewportSize({ width: 360, height: 800 });
  await page.evaluate(() => document.documentElement.style.fontSize = '200%');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '../artifacts/preview-mobile.png', fullPage: true });
  await page.evaluate(() => document.documentElement.style.fontSize = '100%');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Back to your learning space', exact: true }).click();
  await expect(page.locator('.draft-list')).toContainText('Our times tables');
  await page.screenshot({ path: '../artifacts/learning-space.png', fullPage: true });
  const unknown = await page.request.get('/api/does-not-exist');
  expect(unknown.status()).toBe(404);
  expect(unknown.headers()['content-type']).toContain('application/problem+json');
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
  expect(errors).toEqual([]);
});
